/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rifleman.epcalendar.gui;

import java.awt.BorderLayout;
import java.util.Date;

/**
 *
 * @author user01
 */
public class TimePickerPanel extends javax.swing.JPanel {
    TimePicker timePikcer;
    /**
     * Creates new form TimePickerPanel
     */
    public TimePickerPanel() {
        initComponents();
        
        Date d = new Date();
        d.setHours(10);
        d.setMinutes(0);
        timePikcer = new TimePicker("dd-MM-yyyy HH:mm:ss", d);
        this.add(timePikcer, BorderLayout.CENTER);
    }

    public String getValue() {
        return timePikcer.getTime();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
